### PR TITLE
Local Dev Env / Setup all UTXOs for Planet A

### PR DESCRIPTION
**Pull request by johannbarbie**
For planet A:

1. run instructions like in README.md 
    - `yarn`, `yarn build`, `yarn start planetA`
    => should start local environment and prepare coins.
   - or with Docker (see README)
2. start burner wallet in local dev: `npm i`, `npm start`
3. copy printed coin addresses and RPC endpoints from terminal into burner config.
4. use local ganache (should be `http://localhost:8545`) for root chain RPC.
5. import printed priv-key in terminal into local burner.

you should see a balance in burner:

Screen Shot 2019-07-18 at 8 30 08 PM

### CODE REVIEW

**Comment by troggy** [comment]
I've restored all the tests

**Comment by troggy** [comment]
cleaner diff (excluding moved files): https://github.com/leapdao/integration-tests/pull/36/commits/c1cfe28b28c395cc0f252777d12e457e7f551e6c

**Comment by troggy** [comment]
Better docker image to follow in a different PR..

**Comment by pinkiebell** [comment]
> Better docker image to follow in a different PR..

😃

**Pull request merged**
